### ISSUE TITLE
Errors occur with settings in ~/.rspec

### ISSUE THREAD

**Issue by pirj** [rspec/rspec-dev#217]
`rspec-dev` as of 86c75d1315.

I have a couple settings in my `~/.rspec` file that results in weird failures when running `rake`.

## `--require pry`

> When working with gems, and `pry` is specified in `Gemfile.local`, it's not automatically required and setting a breakpoint in the code requires to `require pry; binding.pry`, which is painful.

Results in (when running `rake`):
```
 (RSpec::Expectations::ExpectationNotMetError)
features/verifying_doubles/partial_doubles.feature:34:in `Then the output should contain "1 example, 1 failure"'

Exit status was 1 but expected it to be 0. Output:


An error occurred while loading pry.
Failure/Error: __send__(method, file)

LoadError:
  cannot load such file -- pry
# /Users/pirj/source/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:2034:in `require'
# /Users/pirj/source/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:2034:in `load_file_handling_errors'
# /Users/pirj/source/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1519:in `block in requires='
```

Mitigation: add
```
group :development do
  gem 'pry-byebug'
end
```
to `Gemfile-custom` in `repo/*`.

This technique doesn't work with `bin/cucumber` - fails to load `pry` anyway, tried to specify group as `:development, :cucumber` to no avail.

## `--profile 2`

Running `rake` results in:
```
  6) RSpec::Core::Formatters::ProgressFormatter produces the expected full output
     Failure/Error:
           expect(output).to eq(<<-EOS.gsub(/^\s+\|/, ''))
             |**F..FFFFF
             |
             |#{expected_summary_output_for_example_specs}

           EOS

       expected: "**F..FFFFF\n\nPending: (Failures listed here are expected and do not affect your suite's status)\n\n...ources/formatter_specs.rb:71 # a failing spec with odd backtraces with a `nil` backtrace raises\n\n"
            got: "**F..FFFFF\n\nPending: (Failures listed here are expected and do not affect your suite's status)\n\n...ources/formatter_specs.rb:71 # a failing spec with odd backtraces with a `nil` backtrace raises\n\n"

       (compared using ==)

       Diff:
       @@ -84,6 +84,18 @@
             RuntimeError:
               boom

       +Top 2 slowest examples (n.nnnn seconds, 17.9% of total time):
       +  failing spec fails twice
       +    n.nnnn seconds ./spec/rspec/core/resources/formatter_specs.rb:40
       +  a failing spec with odd backtraces fails with a backtrace that has no file
       +    n.nnnn seconds ./spec/rspec/core/resources/formatter_specs.rb:47
       +
       +Top 2 slowest example groups:
       +  pending command with block format
       +    n.nnnn seconds average (n.nnnn seconds / 2 examples) ./spec/rspec/core/resources/formatter_specs.rb:14
       +  failing spec
       +    n.nnnn seconds average (n.nnnn seconds / 2 examples) ./spec/rspec/core/resources/formatter_specs.rb:35
       +
        Finished in n.nnnn seconds (files took n.nnnn seconds to load)
        10 examples, 6 failures, 2 pending

     # ./spec/rspec/core/formatters/progress_formatter_spec.rb:47:in `block (2 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/sandboxing.rb:7:in `block (2 levels) in <top (required)>'
```

## `--format progress`/`--color`

In `rspec-core`:
```

expected "\nRandomized with seed 5141\n.\n\nTop 1 slowest examples (0.00062 seconds, 24.0% of total time):\n  ...econds (files took 0.14219 seconds to load)\n1 example, 0 failures\n\nRandomized with seed 5141\n\n" to include "Addition\n  works\n"
Diff:
@@ -1,2 +1,13 @@
-Addition\n  works\n
+
+Randomized with seed 5141
+.
+
+Top 1 slowest examples (0.00062 seconds, 24.0% of total time):
+  Addition works
+    0.00062 seconds ./spec/addition_spec.rb:2
+
+Finished in 0.0026 seconds (files took 0.14219 seconds to load)
+1 example, 0 failures
+
+Randomized with seed 5141
 (RSpec::Expectations::ExpectationNotMetError)
features/command_line/init.feature:46:in `But the output from `rspec spec/addition_spec.rb` should be in documentation format'

expected "F\n\nFailures:\n\n  1) failure fails and uses the custom color\n     Failure/Error: expect(2).to eq(...d examples:\n\nrspec ./custom_failure_color_spec.rb:7 # failure fails and uses the custom color\n\n" to include "\e[35mF\e[0m"
Diff:
@@ -1,2 +1,20 @@
-F
+F
+
+Failures:
+
+  1) failure fails and uses the custom color
+     Failure/Error: expect(2).to eq(4)
+
+       expected: 4
+            got: 2
+
+       (compared using ==)
+     # ./custom_failure_color_spec.rb:8:in `block (2 levels) in <top (required)>'
+
+Finished in 0.01537 seconds (files took 0.11778 seconds to load)
+1 example, 1 failure
+
+Failed examples:
+
+rspec ./custom_failure_color_spec.rb:7 # failure fails and uses the custom color
 (RSpec::Expectations::ExpectationNotMetError)
features/formatters/configurable_colors.feature:31:in `Then the failing example is printed in magenta'

Failing Scenarios:
cucumber features/command_line/init.feature:25 # Scenario: Accept and use the recommended settings in `spec_helper` (which are initially commented out)
cucumber features/formatters/configurable_colors.feature:16 # Scenario: Customizing the failure color
```

Do you think it's possible to skip loading the global `~/.rspec` by RSpec under test, since those options seem to affect it in that way?

**Comment by JonRowe** [comment]
Hm, so obviously the global rspec config files (there are a couple) is expected to apply to everything, but your custom options are affecting our test suite. I think the solution here is not to turn off the config, but to ensure our tests can survive such config. 

e.g. Those which are depending on a particular format should probably configure the format they are expecting.

The require is a bit funny though, it's probably a bundler thing...
